### ISSUE TITLE
Example links

### ISSUE THREAD

**Issue by 0x5ECF4ULT** [sk22/spotify-links-to-uris#1]
You should probably remove the links.txt because we all know that Giants can court you for copyright infringement. The whole repo is kind of a risky thing.

**Comment by sk22** [comment]
you think so? i don't think that a reference to a song (even without song title or whatever) is a problem concerning copyright.
and, you mean that the repo is risky because it contains the name 'spotify'? well, since projects using the spotify api featured at https://developer.spotify.com/discover/ have it in their name there.
but thanks for the warning!

**Comment by sk22** [comment]
guess i'm closing this for now (sure, i might be underestimating the whole thing)
